export enum Commands {
    EXIT_KEY = "EXIT",
    DISPLAY_INVENTORY_KEY = "I",
    EXIT_GAME_COMMAND = "EXIT_GAME_COMMAND",
    NEXT_LOCATION_COMMAND = "NEXT_LOCATION_COMMAND",
    TAKE_THING_COMMAND = "TAKE_THING_COMMAND",
    USE_THING_COMMAND = "USE_THING_COMMAND",
    BATTLE_COMMAND = "BATTLE_COMMAND",
    GAME_OVER_COMMAND = "GAME_OVER_COMMAND",
    FINISH_COMMAND = "FINISH_COMMAND",
    DISPLAY_INVENTORY_COMMAND = "DISPLAY_INVENTORY_COMMAND",
}

